homepage:
    path:     /
    defaults: { _controller: RemmyHomeBundle:Home:index }
    methods:  GET

aboutPage:
    path:     /about
    defaults: { _controller: RemmyHomeBundle:Home:about }

cgvPage:
    path:     /cgv
    defaults: { _controller: RemmyHomeBundle:Home:cgv }

contactPage:
    path:     /contact
    defaults: { _controller: RemmyHomeBundle:Home:contact }

sitemapPage:
    path:     /sitemap
    defaults: { _controller: RemmyHomeBundle:Home:sitemap }