<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDdjlvam\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDdjlvam/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDdjlvam.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDdjlvam\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDdjlvam\appDevDebugProjectContainer([
    'container.build_hash' => 'Ddjlvam',
    'container.build_id' => '02cf921f',
    'container.build_time' => 1551652518,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDdjlvam');
