<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQbt7qvj\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQbt7qvj/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerQbt7qvj.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerQbt7qvj\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerQbt7qvj\appProdProjectContainer([
    'container.build_hash' => 'Qbt7qvj',
    'container.build_id' => 'cafa0be9',
    'container.build_time' => 1551305672,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQbt7qvj');
