<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8txrfhx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8txrfhx/appProdProjectContainer.php') {
    touch(__DIR__.'/Container8txrfhx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container8txrfhx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container8txrfhx\appProdProjectContainer(array(
    'container.build_hash' => '8txrfhx',
    'container.build_id' => 'b8beac20',
    'container.build_time' => 1550834520,
), __DIR__.\DIRECTORY_SEPARATOR.'Container8txrfhx');
