<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXdaxnvf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXdaxnvf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXdaxnvf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXdaxnvf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXdaxnvf\appDevDebugProjectContainer([
    'container.build_hash' => 'Xdaxnvf',
    'container.build_id' => 'd237ac90',
    'container.build_time' => 1551392142,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXdaxnvf');
