<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWndy53s\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWndy53s/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWndy53s.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWndy53s\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWndy53s\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Wndy53s',
    'container.build_id' => '970b2484',
    'container.build_time' => 1550928849,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWndy53s');
