<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPxzm0sk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPxzm0sk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPxzm0sk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPxzm0sk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPxzm0sk\appDevDebugProjectContainer([
    'container.build_hash' => 'Pxzm0sk',
    'container.build_id' => '6609750a',
    'container.build_time' => 1551653542,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPxzm0sk');
