<?php

namespace Proxies\__CG__\Remmy\BackOfficeBundle\Entity\backup;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProductStock extends \Remmy\BackOfficeBundle\Entity\backup\ProductStock implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Remmy\\BackOfficeBundle\\Entity\\backup\\ProductStock' . "\0" . 'idstock', '' . "\0" . 'Remmy\\BackOfficeBundle\\Entity\\backup\\ProductStock' . "\0" . 'quantity', '' . "\0" . 'Remmy\\BackOfficeBundle\\Entity\\backup\\ProductStock' . "\0" . 'idcolor', '' . "\0" . 'Remmy\\BackOfficeBundle\\Entity\\backup\\ProductStock' . "\0" . 'idsize', '' . "\0" . 'Remmy\\BackOfficeBundle\\Entity\\backup\\ProductStock' . "\0" . 'productstock'];
        }

        return ['__isInitialized__', '' . "\0" . 'Remmy\\BackOfficeBundle\\Entity\\backup\\ProductStock' . "\0" . 'idstock', '' . "\0" . 'Remmy\\BackOfficeBundle\\Entity\\backup\\ProductStock' . "\0" . 'quantity', '' . "\0" . 'Remmy\\BackOfficeBundle\\Entity\\backup\\ProductStock' . "\0" . 'idcolor', '' . "\0" . 'Remmy\\BackOfficeBundle\\Entity\\backup\\ProductStock' . "\0" . 'idsize', '' . "\0" . 'Remmy\\BackOfficeBundle\\Entity\\backup\\ProductStock' . "\0" . 'productstock'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProductStock $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdstock()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdstock();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdstock', []);

        return parent::getIdstock();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantity($quantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantity', [$quantity]);

        return parent::setQuantity($quantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantity', []);

        return parent::getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcolor(\Remmy\BackOfficeBundle\Entity\backup\Color $idcolor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcolor', [$idcolor]);

        return parent::setIdcolor($idcolor);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcolor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcolor', []);

        return parent::getIdcolor();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdsize(\Remmy\BackOfficeBundle\Entity\backup\Size $idsize = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdsize', [$idsize]);

        return parent::setIdsize($idsize);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdsize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdsize', []);

        return parent::getIdsize();
    }

    /**
     * {@inheritDoc}
     */
    public function addProductstock(\Remmy\BackOfficeBundle\Entity\backup\Product $productstock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductstock', [$productstock]);

        return parent::addProductstock($productstock);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductstock(\Remmy\BackOfficeBundle\Entity\backup\Product $productstock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductstock', [$productstock]);

        return parent::removeProductstock($productstock);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductstock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductstock', []);

        return parent::getProductstock();
    }

}
